### ISSUE TITLE
Fedora - Fix Jekyll package dependency

### ISSUE THREAD

**Issue by abitrolly** [yakshaveinc/linux#6]
Jekyll doesn't work out of the box on Fedora 27.
```
➜  dnf install jekyll
➜  jekyll
/usr/share/rubygems/rubygems/core_ext/kernel_require.rb:55:in `require': cannot load such file -- bundler (LoadError)
	from /usr/share/rubygems/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /usr/share/gems/gems/jekyll-3.2.1/lib/jekyll/plugin_manager.rb:34:in `require_from_bundler'
	from /usr/share/gems/gems/jekyll-3.2.1/exe/jekyll:9:in `<top (required)>'
	from /usr/bin/jekyll:22:in `load'
	from /usr/bin/jekyll:22:in `<main>'
```
Jekyll loads `bundler`, which is missing.
```
➜  bundler
zsh: bundler: command not found...
Install package 'rubygem-bundler' to provide command 'bundler'? [N/y] 
```
Solution is to add `rubygem-bundler` to `jekyll` package dependencies on Fedora.

**Comment by abitrolly** [comment]
@techtonik

**Comment by abitrolly** [comment]
Fixed in Fedora 28.
```
➜ sudo dnf remove rubygem-bundler
Dependencies resolved.
==========================================================================================================================================================================
 Package                                                Arch                            Version                                   Repository                         Size
==========================================================================================================================================================================
Removing:
 rubygem-bundler                                        noarch                          1.16.1-3.fc28                             @fedora                           1.1 M
Removing dependent packages:
 rubygem-jekyll                                         noarch                          3.8.4-1.fc28                              @updates                          401 k
...
```

**Comment by abitrolly** [comment]
The original idea was to provide recipe (SOP) how to handle things like this in a future, but there is no time for it right now. Maybe later.
